services:
  tdd_node_a:
    <<: *tdd-node-common
    ports:
      - 4000:4000 # http
    environment:
      - PORT=4000

  tdd_node_b:
    <<: *tdd-node-common
    ports:
      - 4001:4001 # http
    environment:
      - PORT=4001

  tdd_node_c:
    <<: *tdd-node-common
    ports:
      - 4002:4002 # http
    environment:
      - PORT=4002

  # LGTM includes a collector, so we don't follow example in OTel docs:
  # https://opentelemetry.io/docs/languages/erlang/exporters/#setting-up-the-collector
  lgtm:
    image: grafana/otel-lgtm:0.11.5
    ports:
      - 3000:3000 # Grafana UI
      - 4317:4317 # OTLP gRPC
      - 4318:4318 # OTLP HTTP
    volumes:
      - lgtm_data:/data
    environment:
      # https://github.com/grafana/docker-otel-lgtm/#configuration
      - ENABLE_LOGS_ALL=true

volumes:
  lgtm_data:

x-tdd-node-common: &tdd-node-common
  build:
    context: .
  depends_on:
    - lgtm
  environment:
    - SECRET_KEY_BASE=ZOO9B3CQWdK/kjQmEFmvukqaXkcFpaH7AJItXjBVADrmMPiNr0ETM28TmH1/xVXj
    - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    # https://hexdocs.pm/opentelemetry_exporter/readme.html#os-environment
    - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318
